version: 2.1

references:
  platform-docker: &platform-cicd
    docker:
      - image: objectrocket/platform-cicd:latest
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}

jobs:
  lint_and_test:
    docker:
      - image: circleci/python:3.8
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: |
            poetry install
      - run:
          name: Lint
          command: |
            make lint
      - run:
          name: Test
          command: |
            make test
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/cache
            - /home/circleci/.cache/pypoetry/virtualenvs

  build_deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker login
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            docker info
      - run:
          name: docker build and push
          command: |
            make OR_PYPI_PROD_PASSWORD="${OBJECTROCKET_PYPI_PASSWORD}" docker-build
            make docker-deploy

workflows:
  version: 2
  # runs on all untagged commits
  lint_and_test:
    jobs:
      - lint_and_test:
          filters:
            tags:
              ignore:
                - /^[0-9]+.[0-9]+.[0-9]+$/
                - /^[0-9]+.[0-9]+.[0-9]+rc[0-9]+$/
            branches:
              ignore: develop
